PACKAGE_TARNAME = papi
prefix = /lustre/home/acct-hpc/hpcwj/tmp/papi-x86/src/install
exec_prefix = ${prefix}
datarootdir = ${prefix}/share
datadir = ${datarootdir}/${PACKAGE_TARNAME}
DATADIR = $(DESTDIR)$(datadir)
INCLUDE = -I. -I${prefix}/include
CC	= icc
F77	= ifort
CC_R	= $(CC) -pthread
CFLAGS	=  -g -diag-disable 188,869,271  -O1

